### ISSUE TITLE
presentation compiler support

### ISSUE THREAD

**Issue by fommil** [oleg-py/better-monadic-for#1]
this project looks very interesting!

However my primary concern is that it will break position information. Could you please add https://github.com/ensime/pcplod tests to your test suite?

Further examples in kind-projector and https://gitlab.com/fommil/scalaz-deriving/tree/master/deriving-plugin/src

**Comment by oleg-py** [comment]
@fommil thanks for the pointer. I will make it my priority together with proper README.

**Comment by fommil** [comment]
in fact a good semantic highlighting test would be perfect but pcplod does not support that yet (it's fairly easy to add the support).

**Comment by oleg-py** [comment]
@fommil this should be fixed by now. I'm not very familiar with presentation compiler, so reopen the issue if something else is broken.
