### ISSUE TITLE
Anonymous variable flagged as error

### ISSUE THREAD

**Issue by sdavidp** [oleg-py/better-monadic-for#12]
Using Scala 2.12.7,
```
[error] [snip]/Server.scala:29:7: parameter value x$2 in value $anonfun is never used
[error]       _ <- Stream.eval(foo)
[error]       ^
```
where _foo_ is a function returning `F[Unit]`
I haven't been able to reproduce the issue with a simple code example but Chris Davenport (who identified _better-monadic-for_ as the culprit) thinks it is a problem with the macro expansion.
E.g., in our piece of code if I have two such lines above the error is flagged on the 2nd one, even if I swap their order in the for-comprehension.

This was seen using releases 0.2.4 and 0.3.0-M2.

**Comment by oleg-py** [comment]
@sdavidp thanks for the report, I'll take a look this weekend.

In the meantime, can you try adding `-P:bm4:no-tupling:n` to `scalacOptions` and see if it fixes the problem?

**Comment by sdavidp** [comment]
@oleg-py Yes it does. Thank you Oleg!

**Comment by oleg-py** [comment]
I published the 0.3.0-M3 version just now. Give it some time to sync to Maven, and try it out without disabling untupler - should work properly now.

**Comment by sdavidp** [comment]
No Oleg, still get the error with 0.3.0-M3.

**Comment by oleg-py** [comment]
I derped and used wrong bitwise operator. My apologies! M4 is on its way - it seems to work in the code samples I managed to discover.

If it doesn't work, I'll switch to working it in snapshots. If so, please provide the structure of your for-comprehensions - just obscure the variable names and replace the RHS of each bindings by ???, I'll figure it from here

**Comment by sdavidp** [comment]
-M4 did the trick, for me anyway :)
Thank you Oleg!

**Comment by oleg-py** [comment]
Ok, thanks for keeping me informed :)
