### ISSUE TITLE
implicit val? 

### ISSUE THREAD

**Issue by kailuowang** [oleg-py/better-monadic-for#13]
suppose we have 
```def getYs(implicit x: X): Y = ???```

would it be possible to desugar 
```scala
for {
  implicit x <- xs
  y <- getYs
} yield y
```
to 
```scala
xs.flatMap(implicit x => getYs)
```

**Comment by kailuowang** [comment]
Of course, there is not much need for this particular case for this desugar, but if `getYs` has multiple implicit arguments and `x` is the only missing one, this would be handy.

**Comment by oleg-py** [comment]
@kailuowang that's already in `0.3.0-M2` version. The syntax with `implicit` keyword is not valid, and I cannot change that, and for `=` bindings type is required, but otherwise...
```scala
for {
  implicit0(x: X) <- xs
  y <- getYs
} yield y
```

**Comment by kailuowang** [comment]
Got it. Still pretty amazing. thanks!
