### ISSUE TITLE
Proposal: Allow ending a `for` without a `yield`. 

### ISSUE THREAD

**Issue by diesalbla** [oleg-py/better-monadic-for#14]
In Scala code, I often come across `for`-comprehensions, for any container type with the `flatMap` operation, in which the result of the last expression is then passed directly to the `yield`: 
```Scala
for {
  x <- fili( /***/ (
  y =   kili(x, /***/)
  z <- ori( x, y, /***/)
} yield z
```
The problem, IMHO, is that this becomes a bit redundant. For some simple cases, in which the last expression has not too many variables, it is possible to replace it with `flatMap`, particularly if using  operators like  `>>=`, or `*>`. However, this is not so elegant once one needs several variables at the left-hand-side of a line in the `for`.

In this issue, I propose as a solution, to add to this plugin the ability to interpret a `for` comprehensions without `yield` statements, in which the last expression in the comprehension may be any expression that has the same type as the whole `for`-comprehension. For example, the one above would become: 
```Scala
for {
  x <- fili( /***/ (
  y =  kili(x, /***/)
} ori(x, y, /***/)
```
I a not sure how feasible this solution would be. Scala's syntax allows [for-comprehensions without the yield](https://docs.scala-lang.org/tour/for-comprehensions.html), like the one above, although limited to impure actions. What this issue proposes is to adapt that syntax to the case at hand. 

**Aside: Haskell:** This suggestion is inspired by Haskell's `do`-notation. Although common examples usually show the last operation being a `return`, that is not a syntactic restriction. In truth, for a `do` expression of type `F[A]`, all that is required is that the type of the last expression in the block be of type `F[Int]`. In their case,  `return` is not a reserved word of the language, but a function of the `Monad` type class (like `pure` in Scala-cats).

**Comment by oleg-py** [comment]
I thought about it for a while, and I think it shouldn't be done. For good or bad, we already have this syntax taken by `foreach`, and I want the plugin to avoid breaking changes for as much as possible. For now semantic changes are very minimal, removing one case of fairly surprised and underused behavior and introducing a single new keyword `implicit0`.

Additionally, with `map` elimination you are able to write a monadic-recursive expression as a for-comprehension without memory leaks. So it all boils down to syntactic convenience, which is IMO not worth breaking even more existing semantics.
