### ISSUE TITLE
false positive unused parameter value

### ISSUE THREAD

**Issue by yanns** [oleg-py/better-monadic-for#17]
when using the plugin with for comprehension about tasks, I had the following warnings:
```
[warn] XXXX.scala:369:7: parameter value x$15 in value $anonfun is never used
[warn]       _     <- someTask
[warn]       ^
[warn] one warning found
```

**Comment by oleg-py** [comment]
@yanns which plugin/Scala version you are using? Try 0.3.0-M4 (I know, I need to update the readme :)

**Comment by yanns** [comment]
I'm using the version `0.2.4`.
The version `0.3.0-M4` is working great, thx!

Yes, an updated README would be great. (and notes on https://github.com/oleg-py/better-monadic-for/releases)
