### ISSUE TITLE
Support for 2.13?

### ISSUE THREAD

**Issue by djspiewak** [oleg-py/better-monadic-for#18]
I'm quite in love with this plugin. However, without support for 2.13, it's hard for me to just go ahead and enable it on all my projects. Consider this a feature request. :-)

**Comment by oleg-py** [comment]
The 0.3.0-M4 is cross-compiled for 2.13.0-M5 now and is available on maven central. In theory that should be also compatible with previous milestone releases of 2.13, tho you won't be able to use %% in `libraryDependencies`

**Comment by djspiewak** [comment]
For the record, it isn't compatible with M4. :-)
