### ISSUE TITLE
What is the 0.2.4 release?

### ISSUE THREAD

**Issue by mcanlas** [oleg-py/better-monadic-for#20]
According to Maven there is a `0.2.4` but that isn't listed as a release here in Github. Should we use it?

https://mvnrepository.com/artifact/com.olegpy/better-monadic-for

**Comment by oleg-py** [comment]
@mcanlas the recommended version is `0.3.0-M4` - I had an M tag because I expected there to be edge cases / bugs in `implicit0` implementation, but there weren't any 😄 .
