### ISSUE TITLE
Optimization: remove final `map` calls if provided function is identity

### ISSUE THREAD

**Issue by oleg-py** [oleg-py/better-monadic-for#3]
As mentioned by @fommil in #2, in for-comprehensions of following structure:

```scala
for {
  _ <- doA
  b <- doB
  c <- doSomethingWithB(b)
} yield c
```
The desugaring is equivalent to:

```scala
doA.flatMap(_ => doB.flatMap(b => doSomethingWith(b).map(c => c)))
```

For any lawful functor, the `map` is redundant and may be eliminated, saving on memory and things like thread-shifting on `Future`.

* Optimization should happen only if the lambda generated is exactly `(ident => ident)`. A type ascription on any of those lines might be a widening conversion, so it cannot be removed (at least for now).
* Optimization should live under an option, so it can be disabled if edge cases pop up or people require `map` with side-effects
* Ideally (but might not be possible) it should be limited to for-comprehensions.
* Optimization should happen only inside a `flatMap` to prevent silliness like this from compiling:
```scala
for { x <- 42 }  yield x
```
Sure there is an identity functor and all, but it won't work when you start adding more generators, so let's not do it.

**Comment by fommil** [comment]
I hadn't considered some of these cases, your assumptions sound solid :+1:

**Comment by oleg-py** [comment]
I have achieved a decent level of success in doing the transformations post-typer. (cf530fccd29dec5ce2f0098d38ae6b1ad816ff6a)

Things that it can do better than parser version:
1. Can erase map with type ascription if it doesn't affect the type returned.
2. Can erase `.map((_: Unit) => ())` reliably (only if the type of ignored variable is really Unit).
3. No need to care about `for { x <- 42 } yield x` case as it would already be rejected by the typer.

There are downsides to this, of course:
* Working on typed trees is harder, since you need to preserve the mutable `tpe` field, or you'll get a compiler crash in later stage. Luckily patterns are fairly simple due to point 3 above.
* After typer all implicit conversions are applied, so there's now a number of patterns that need to be matched (regular `map` method, `map` that takes a `CanBuildFrom` and `map` as extension method).

I tested that generic code works with Scalaz 7 and Cats. It's likely to not detect zero-cost enrichments coming in Scalaz 8, however, and the latter hasn't yet a published version. I need to investigate on how to make it work - worst case I can add a post-parser version too. But I believe this can wait, at least a little :)

**Comment by fommil** [comment]
Woohoo! Do you have any simple benchmarks for this? I'm looking forward to trying it out.
