### ISSUE TITLE
publish on maven central

### ISSUE THREAD

**Issue by fommil** [oleg-py/better-monadic-for#5]
please publish on maven central, I can't use this at work because only specific repos are proxied via our corporate firewall and we cannot use custom repos directly.

**Comment by oleg-py** [comment]
Will be done ASAP.

I never published anything to maven central before. I have recently submitted a request for OSSRH, so now it's just a matter of waiting for approval on their side (and me figuring out the rest :). Hoping it won't take too long.

**Comment by fommil** [comment]
thank you! It is really awkward the first time but very simple thereafter. I recommend the sbt-sonatype plugin. When I am releasing anything I use `sbt +publishSigned sonatypeRelease` with no further actions necessary, helped by my setup https://gitlab.com/fommil/sbt-sensible/blob/master/src/main/scala/SonatypePlugin.scala

BTW, I am very impressed by this plugin. I have added a section about it to my book.

**Comment by fommil** [comment]
an aside in https://leanpub.com/fpmortals/read#leanpub-auto-syntax-sugar

**Comment by oleg-py** [comment]
Finally published the plugin to Maven Central. Readme updated.

**Comment by fommil** [comment]
thank you!
