### ISSUE TITLE
Optimisation: map fusion

### ISSUE THREAD

**Issue by fommil** [oleg-py/better-monadic-for#6]
```scala
.map(a).map(b).map(c) => .map(f => c(b(a(f))))
```

**Comment by Daenyth** [comment]
Is it possible for this to be conditional on Functor evidence? This is safe for lawful functors but general `map` operations might not make this safe

**Comment by fommil** [comment]
@Daenyth if applied after typing it might be more the case that some `.map`s are good and others are bad, which the user could provide via a regex I should imagine.

**Comment by AesaKamar** [comment]
I bet compile-time optimizations using ScalaZ or Cats could be a whole other layer unto itself.

**Comment by pjrt** [comment]
Could we not make some Scalaz/Cats optimizer? Then we can work on Functor, not `map`. But that would be a different tool.

**Comment by fommil** [comment]
I forgot to close this... go see https://github.com/scalaz/scalaz-plugin
